#config.py
# Database Configuration
SQLALCHEMY_DATABASE_URI = 'mysql://USER:PASSWORD@HOST/DB'
SQLALCHEMY_TRACK_MODIFICATIONS = False

# MySQL Configuration
MYSQL_HOST='HOST'
MYSQL_USER='USER'
MYSQL_PASSWORD = 'PASSWORD'
MYSQL_DB = 'DB'
MYSQL_CURSORCLASS = 'MYSQL_CURSORCLASS'

# Secret Key
SECRET_KEY = 'SECRET_KEY'
